[2025-06-28T17:10:25.926+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-28T17:10:25.941+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_etl.load_data manual__2025-06-28T17:10:18.745975+00:00 [queued]>
[2025-06-28T17:10:25.951+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_etl.load_data manual__2025-06-28T17:10:18.745975+00:00 [queued]>
[2025-06-28T17:10:25.951+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-28T17:10:25.960+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-06-28 17:10:18.745975+00:00
[2025-06-28T17:10:25.968+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=377) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-28T17:10:25.969+0000] {standard_task_runner.py:63} INFO - Started process 379 to run task
[2025-06-28T17:10:25.970+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_etl', 'load_data', 'manual__2025-06-28T17:10:18.745975+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/sales_etl.py', '--cfg-path', '/tmp/tmprz9fh2ed']
[2025-06-28T17:10:25.971+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask load_data
[2025-06-28T17:10:26.008+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_etl.load_data manual__2025-06-28T17:10:18.745975+00:00 [running]> on host 2c170f0bdbf7
[2025-06-28T17:10:26.073+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sales_etl' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-28T17:10:18.745975+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-28T17:10:18.745975+00:00'
[2025-06-28T17:10:26.075+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-28T17:10:26.085+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-06-28T17:10:26.096+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-28T17:10:26.096+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/sales_etl.py", line 65, in load_to_postgres
    (row['region'], row['total_sales'])
                    ~~~^^^^^^^^^^^^^^^
KeyError: 'total_sales'
[2025-06-28T17:10:26.103+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sales_etl, task_id=load_data, run_id=manual__2025-06-28T17:10:18.745975+00:00, execution_date=20250628T171018, start_date=20250628T171025, end_date=20250628T171026
[2025-06-28T17:10:26.110+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task load_data ('total_sales'; 379)
[2025-06-28T17:10:26.151+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-28T17:10:26.162+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-28T17:10:26.163+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
